# Generated by Django 4.2.7 on 2026-02-11 09:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorearnings',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectorearnings',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectorearnings',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectorpickup',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectorpickup',
            name='distance_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectorpickup',
            name='proof_photo',
            field=models.ImageField(blank=True, help_text='Photo proof of completed pickup', null=True, upload_to='collector/proof/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='collectorpickup',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
    ]
