# Generated by Django 4.2.7 on 2026-02-12 14:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_photopost_eco_points_awarded_and_more'),
        ('collector', '0002_alter_collectorearnings_available_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorPickupPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('distance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('handling_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_km', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(limit_choices_to={'is_collector': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_payments', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_payment', to='client.photopost')),
            ],
            options={
                'verbose_name': 'Pickup Payment',
                'verbose_name_plural': 'Pickup Payments',
                'db_table': 'collector_pickup_payment',
            },
        ),
    ]
