# Generated by Django 4.2.7 on 2026-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_collectorpickuppayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorpickup',
            name='trip_start_at',
            field=models.DateTimeField(blank=True, help_text="When collector clicked 'Start Trip'", null=True),
        ),
    ]
