# Generated by Django 4.2.7 on 2026-02-07 18:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, help_text="User's email address (used for login)", max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, help_text='Unique username', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text="User's first name", max_length=50)),
                ('last_name', models.CharField(help_text="User's last name", max_length=50)),
                ('phone_number', models.CharField(help_text='10-digit Indian mobile number', max_length=15)),
                ('is_client', models.BooleanField(default=False, help_text='User is a client (uploads e-waste)')),
                ('is_vendor', models.BooleanField(default=False, help_text='User is a vendor (recycles e-waste)')),
                ('is_collector', models.BooleanField(default=False, help_text='User is a collector (picks up e-waste)')),
                ('is_staff', models.BooleanField(default=False, help_text='User can access admin site')),
                ('is_active', models.BooleanField(default=False, help_text='User account is active (set to True after email verification)')),
                ('is_superuser', models.BooleanField(default=False, help_text='User has all permissions')),
                ('is_admin', models.BooleanField(default=False, help_text='User is an admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date and time when user registered')),
                ('last_login', models.DateTimeField(blank=True, help_text='Date and time of last login', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of last profile update')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts_account',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Registered company name', max_length=200)),
                ('business_address', models.TextField(blank=True, help_text='Complete business address')),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name', max_length=100)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate contact number', max_length=15)),
                ('latitude', models.FloatField(blank=True, help_text='Business location latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Business location longitude', null=True)),
                ('profile_photo', models.ImageField(blank=True, default='vendor_profiles/default.png', help_text='Company/person photo', null=True, upload_to='vendor_profiles/')),
                ('business_license', models.FileField(blank=True, help_text='Business registration license (PDF or image, max 5MB)', null=True, upload_to='vendor/business_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('gst_certificate', models.FileField(blank=True, help_text='GST registration certificate (PDF or image, max 5MB)', null=True, upload_to='vendor/gst_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('ewaste_authorization', models.FileField(blank=True, help_text='E-Waste Recycling Authorization from CPCB (PDF or image, max 5MB)', null=True, upload_to='vendor/ewaste_auth/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('id_proof', models.FileField(blank=True, help_text='ID proof - Aadhaar/PAN/Driving License (PDF or image, max 5MB)', null=True, upload_to='vendor/id_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_verified', models.BooleanField(default=False, help_text='Admin has verified this vendor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Vendor user account', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Details',
                'verbose_name_plural': 'Vendor Details',
                'db_table': 'accounts_vendordetails',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(blank=True, help_text='6-digit OTP code', max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was generated')),
                ('otp_expires_at', models.DateTimeField(help_text='When OTP expires (10 minutes from creation)')),
                ('is_verified', models.BooleanField(default=False, help_text='Email has been verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When email was verified', null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of OTP verification attempts')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum allowed attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Last verification attempt time', null=True)),
                ('resend_count', models.IntegerField(default=0, help_text='Number of times OTP was resent')),
                ('last_resend_at', models.DateTimeField(blank=True, help_text='Last OTP resend time', null=True)),
                ('user', models.OneToOneField(help_text='User associated with this verification', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'accounts_emailverification',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text="Client's gender (optional)", max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (optional)', null=True)),
                ('address', models.TextField(blank=True, help_text='Complete address (optional)')),
                ('profile_photo', models.ImageField(blank=True, default='client_profiles/default.png', help_text='Profile photo (optional)', null=True, upload_to='client_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Client user account', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'db_table': 'accounts_clientprofile',
            },
        ),
        migrations.CreateModel(
            name='ProfileCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info_complete', models.BooleanField(default=False, help_text='Basic information is complete')),
                ('documents_uploaded', models.BooleanField(default=False, help_text='Required documents are uploaded')),
                ('profile_submitted', models.BooleanField(default=False, help_text='Profile has been submitted for review')),
                ('completion_percentage', models.IntegerField(default=0, help_text='Profile completion percentage (0-100)')),
                ('missing_fields', models.JSONField(blank=True, default=list, help_text='List of missing required fields')),
                ('admin_reviewed', models.BooleanField(default=False, help_text='Admin has reviewed this profile')),
                ('approval_status', models.CharField(choices=[('incomplete', 'Profile Incomplete'), ('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Needs Resubmission')], db_index=True, default='incomplete', help_text='Current approval status', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, help_text="Admin's remarks about the profile")),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When profile was submitted for review', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When profile was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User associated with this profile completion tracker', on_delete=django.db.models.deletion.CASCADE, related_name='profile_completion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Completion',
                'verbose_name_plural': 'Profile Completions',
                'db_table': 'accounts_profilecompletion',
                'indexes': [models.Index(fields=['approval_status'], name='accounts_pr_approva_b52c69_idx'), models.Index(fields=['profile_submitted'], name='accounts_pr_profile_a59eea_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text='Complete residential address')),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike/Motorcycle'), ('scooter', 'Scooter'), ('auto', 'Auto Rickshaw'), ('van', 'Van/Small Truck'), ('tempo', 'Tempo'), ('pickup', 'Pickup Truck')], help_text='Type of vehicle for collecting e-waste', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number (e.g., MH12AB1234)', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile photo (JPG/PNG, max 5MB)', null=True, upload_to='collector/profile_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('driving_license', models.FileField(blank=True, help_text='Valid driving license (PDF or image, max 5MB)', null=True, upload_to='collector/driving_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('aadhaar_card', models.FileField(blank=True, help_text='Aadhaar card copy (PDF or image, max 5MB)', null=True, upload_to='collector/aadhaar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('vehicle_rc', models.FileField(blank=True, help_text='Vehicle Registration Certificate (PDF or image, max 5MB)', null=True, upload_to='collector/vehicle_rc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Collector user account', on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collector Profile',
                'verbose_name_plural': 'Collector Profiles',
                'db_table': 'accounts_collectorprofile',
                'indexes': [models.Index(fields=['vehicle_type'], name='accounts_co_vehicle_9af366_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_ac_usernam_862e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_client', 'is_vendor', 'is_collector'], name='accounts_ac_is_clie_d4b6b9_idx'),
        ),
    ]
