# Generated by Django 4.2.7 on 2026-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilecompletion_rejection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude (optional)', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude (optional)', null=True),
        ),
    ]
