# Generated by Django 4.2.7 on 2026-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendordetails_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Primary contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Full name of the collector', max_length=100),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text="Collector's gender", max_length=20),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='use_registration_details',
            field=models.BooleanField(default=True, help_text='Use details provided during registration (Name/Phone)'),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='ewaste_auth_type',
            field=models.CharField(choices=[('spcb', 'SPCB Authorization'), ('cpcb', 'CPCB EPR Registration'), ('cto', 'Consent to Operate (CTO)'), ('hazardous', 'Hazardous Waste Authorization')], default='cpcb', help_text='Type of e-waste authorization document', max_length=20),
        ),
    ]
