# Generated by Django 4.2.7 on 2026-03-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_collectorprofile_alternate_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorprofile',
            name='profile_photo',
        ),
    ]
