# Generated by Django 4.2.7 on 2026-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_collectorprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='collector_profiles/default.png', help_text='Collector photo (optional)', null=True, upload_to='collector_profiles/'),
        ),
    ]
