# Generated by Django 4.2.7 on 2026-02-08 08:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='18:00')),
                ('operating_days', models.JSONField(default=list, help_text='List of operating days')),
                ('is_active', models.BooleanField(default=True)),
                ('max_daily_capacity', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_collectioncenter',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appreciationpoints',
            name='current_tier',
            field=models.CharField(choices=[('casual', 'Casual Recycler'), ('regular', 'Regular Recycler'), ('champion', 'Eco Champion'), ('hero', 'Eco Hero'), ('legend', 'Eco Legend')], default='casual', max_length=20),
        ),
        migrations.AddField(
            model_name='appreciationpoints',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appreciationpoints',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='appreciationpoints',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='appreciation_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for earn, negative for redeem')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned Points'), ('redeem', 'Redeemed Points'), ('bonus', 'Bonus Points'), ('adjustment', 'Admin Adjustment')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_pointtransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Photo of e-waste item', upload_to='e-photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('title', models.CharField(help_text='Brief title/description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description (optional)')),
                ('quantity', models.IntegerField(default=1, help_text='Number of items', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('address', models.TextField(help_text='Pickup address')),
                ('latitude', models.FloatField(help_text='GPS latitude')),
                ('longitude', models.FloatField(help_text='GPS longitude')),
                ('ai_category', models.CharField(blank=True, choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tv', 'Television'), ('battery', 'Battery'), ('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine'), ('ac', 'Air Conditioner'), ('appliance', 'Small Appliance'), ('cable', 'Cables/Wires'), ('electronics', 'Other Electronics')], help_text='AI-detected category', max_length=50)),
                ('ai_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent (Like New)'), ('good', 'Good (Minor Wear)'), ('fair', 'Fair (Some Damage)'), ('poor', 'Poor (Not Working)')], help_text='AI-detected condition', max_length=20)),
                ('ai_estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='AI estimated value in ₹', max_digits=10, null=True)),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('tier', models.CharField(blank=True, choices=[('high', 'High Value (₹500+)'), ('medium', 'Medium Value (₹100-499)'), ('low', 'Low Value (<₹100)')], help_text='Pricing tier', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Vendor Assignment'), ('assigned', 'Assigned to Vendor'), ('accepted', 'Accepted by Vendor'), ('pickup_scheduled', 'Pickup Scheduled'), ('collected', 'Collected by Collector'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('vendor_remarks', models.TextField(blank=True)),
                ('vendor_final_value', models.DecimalField(blank=True, decimal_places=2, help_text='Final value determined by vendor', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collector', models.ForeignKey(blank=True, limit_choices_to={'is_collector': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='photo_posts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_photopost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bulk E-Waste Pickup', max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('item_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('collecting', 'Collecting Items (< 5)'), ('ready', 'Ready for Pickup (5+)'), ('scheduled', 'Pickup Scheduled'), ('completed', 'Completed')], default='collecting', max_length=20)),
                ('ready_for_pickup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collector', models.ForeignKey(blank=True, limit_choices_to={'is_collector': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_collections', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='bulk_pickup_group', to='client.photopost')),
                ('user', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_bulkpickup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='photopost',
            index=models.Index(fields=['-created_at'], name='client_phot_created_ec446c_idx'),
        ),
        migrations.AddIndex(
            model_name='photopost',
            index=models.Index(fields=['status'], name='client_phot_status_2004cd_idx'),
        ),
        migrations.AddIndex(
            model_name='photopost',
            index=models.Index(fields=['tier'], name='client_phot_tier_4d1845_idx'),
        ),
        migrations.AddIndex(
            model_name='photopost',
            index=models.Index(fields=['user', '-created_at'], name='client_phot_user_id_c3e0b8_idx'),
        ),
    ]
