# Generated by Django 4.2.7 on 2026-02-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_collectioncenter_appreciationpoints_current_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='eco_points_awarded',
            field=models.IntegerField(default=0, help_text='Eco-points if item has no monetary value'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='evaluation_date',
            field=models.DateTimeField(blank=True, help_text='When vendor evaluated the item', null=True),
        ),
        migrations.AddField(
            model_name='photopost',
            name='evaluation_type',
            field=models.CharField(blank=True, choices=[('repair', 'Repairable'), ('recycle', 'Recyclable'), ('ecopoints', 'Eco-Points Only')], help_text="Vendor's evaluation after inspection", max_length=20),
        ),
    ]
