# Generated by Django 4.2.7 on 2026-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_return_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='delivery_otp',
            field=models.CharField(blank=True, default='', help_text='6-digit OTP shown to vendor; collector enters at delivery to confirm handover', max_length=6),
        ),
        migrations.AddField(
            model_name='photopost',
            name='pickup_otp',
            field=models.CharField(blank=True, default='', help_text='6-digit OTP shown to client; collector enters at pickup to verify identity', max_length=6),
        ),
        migrations.AlterField(
            model_name='evaluationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='condition_notes',
            field=models.TextField(blank=True, help_text="Vendor's physical condition observations"),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='price_breakdown',
            field=models.TextField(blank=True, help_text='How vendor calculated the offer price'),
        ),
    ]
