# Generated by Django 4.2.7 on 2026-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_photopost_weight_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('monitor', 'Monitor'), ('smartphone', 'Smartphone'), ('battery', 'Battery & Charger'), ('appliance', 'Home Appliance'), ('other', 'Computer Accessory')], help_text='AI-detected category', max_length=50),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='ai_confidence',
            field=models.FloatField(default=0.0, help_text='AI prediction confidence (0-100)'),
        ),
    ]
