# Generated by Django 4.2.7 on 2026-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_photopost_ai_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('monitor', 'Monitor & TV'), ('smartphone', 'Smartphone'), ('battery', 'Battery & Charger'), ('appliance', 'Large Appliance'), ('other', 'Computer Accessory')], help_text='AI-detected category', max_length=50),
        ),
    ]
