# Generated by Django 4.2.7 on 2026-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_photopost_ai_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationhistory',
            name='client_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationhistory',
            name='client_choice',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted Offer'), ('rejected', 'Requested Re-evaluation'), ('return', 'Requested Return'), ('transfer', 'Transferred to New Vendor')], max_length=20, null=True),
        ),
    ]
