# Generated by Django 4.2.7 on 2026-02-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_evaluationhistory_client_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationhistory',
            name='client_requested_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
