# Generated by Django 4.2.7 on 2026-03-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_evaluationhistory_client_requested_value'),
        ('payments', '0002_wallet_is_active_wallet_total_withdrawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='photo_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='client.photopost'),
        ),
    ]
